### ISSUE TITLE
Feature request: Annotate the output VFile with exported symbols.

### ISSUE THREAD

**Issue by ggoodman** [wooorm/xdm#7]
## Use-case

Suppose I have an mdx file like:

```mdx
export const name = "ggoodman";

# Hello world
```

The resulting JavaScript will be an ES Module having a default export that is a react function component and a named export `name`. It would be possible to use this information at compile-time to generate type definitions for the `.mdx` file with accurate export names.

**Comment by ChristianMurphy** [comment]
Assuming you mean `xdm.compile`. This is already supported when TypeScript is configured with `"allowJs": true`, as the export's type can be statically inferred.

If you mean `xdm.evaluate` it is theoretically possible, with template types, but it would mean a second parallel markdown and jsx parser, which would be incredibly complex, and likely make building pages incredibly slow. (https://github.com/codemix/ts-sql gives a baseline of how complex the typings would be, and that is with a language that has a grammar that can be fully represented in EBNF, markdown does not)

**Comment by wooorm** [comment]
@ChristianMurphy did you switch up `evaluate` and `compile`? 🤔

---

`xdm.evaluate` already returns all exports: https://github.com/wooorm/xdm#returns-1
It can do that because imports are not supported.

For compile, which supports ESM in full, it would be impossible to know because:

```
export * from "./some/place.js"

# Hello world
```

**Comment by wooorm** [comment]
> It would be possible to use this information at compile-time to generate type definitions for the .mdx file with accurate export names.

How would knowing about `name` help you here? Because it would still be unclear what its value is?

**Comment by ggoodman** [comment]
I totally forgot about the `export * from '...'` case. Sounds like this isn't possible.

**Comment by ChristianMurphy** [comment]
> did you switch up `evaluate` and `compile`?

I should clarify that when I say `compile` I specifically mean `compile`, write the file to disk, then start another `tsc` process.
But generally, no I don't think the two are confused above.
`evaluate` is incredibly complex to get fully resolved static types, as you'd need to teach typescript how to parse MD/MDX.
`compile` is relatively simple because TypeScript already knows how to parse the JS output from the compile step and infer types.

> I totally forgot about the export * from '...' case. Sounds like this isn't possible.

again, it really depends on your build process.
If you `xdm.compile`

```js
export * from 'lodash'

# header
```

take the output JS file, and push it through another `tsc` process with `"allowJs": true` it will infer all of the exported properties from `lodash` just fine.
If you try to compile and run in the same tsc process (either using `evaluate` or another means) it will not infer them, and the process for inference is rather complex, as outlined above.
